CREATE TABLE `countries` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name_en` varchar(100) NOT NULL DEFAULT '',
  `name_de` varchar(100) NOT NULL DEFAULT '',
  `name_fr` varchar(100) NOT NULL DEFAULT '',
  `name_it` varchar(100) NOT NULL DEFAULT '',
  `name_es` varchar(100) NOT NULL DEFAULT '',
  `name_ru` varchar(100) NOT NULL DEFAULT '',
  `alpha_2` varchar(2) NOT NULL DEFAULT '',
  `alpha_3` varchar(3) NOT NULL DEFAULT ''
) DEFAULT CHARSET=utf8;


INSERT INTO `countries` (`id`, `name_en`, `name_de`, `name_fr`, `name_it`, `name_es`, `name_ru`, `alpha_2`, `alpha_3`) VALUES
(1, 'Afghanistan', 'Afghanistan', 'AFGHANISTAN', 'Afghanistan', 'Afganistán', 'Афганистан', 'AF', 'AFG'),
(2, 'Aland Islands', 'Åland', 'ÅLAND, ÎLES', 'Isole Åland', 'Åland, Islas', 'Аландские острова', 'AX', 'ALA'),
(3, 'Albania', 'Albanien', 'ALBANIE', 'Albania ', 'Albania', 'Албания', 'AL', 'ALB'),
(4, 'Algeria', 'Algerien', 'ALGÉRIE', 'Algeria', 'Argelia', 'Алжир', 'DZ', 'DZA'),
(5, 'American Samoa', 'Amerikanisch-Samoa', 'SAMOA AMÉRICAINES', 'Samoa Americane', 'Samoa Americana', 'Американское Самоа', 'AS', 'ASM'),
(6, 'Andorra', 'Andorra', 'ANDORRE', 'Andorra', 'Andorra', 'Андорра', 'AD', 'AND'),
(7, 'Angola', 'Angola', 'ANGOLA', 'Angola ', 'Angola', 'Ангола', 'AO', 'AGO'),
(8, 'Anguilla', 'Anguilla', 'ANGUILLA', 'Anguilla', 'Anguila', 'Ангилья', 'AI', 'AIA'),
(9, 'Antarctica', 'Antarktika', 'ANTARCTIQUE', 'Antartide ', 'Antártida', 'Антарктида', 'AQ', ''),
(10, 'Antigua and Barbuda', 'Antigua und Barbuda', 'ANTIGUA-ET-BARBUDA', 'Antigua e Barbuda', 'Antigua y Barbuda', 'Антигуа и Барбуда', 'AG', 'ATG'),
(11, 'Argentina', 'Argentinien', 'ARGENTINE', 'Argentina ', 'Argentina', 'Аргентина', 'AR', 'ARG'),
(12, 'Armenia', 'Armenien', 'ARMÉNIE', 'Armenia ', 'Armenia', 'Армения', 'AM', 'ARM'),
(13, 'Aruba', 'Aruba', 'ARUBA', 'Aruba', 'Aruba', 'Аруба', 'AW', 'ABW'),
(14, 'Australia', 'Australien', 'AUSTRALIE', 'Australia', 'Australia', 'Австралия', 'AU', 'AUS'),
(15, 'Austria', 'Österreich', 'AUTRICHE', 'Austria', 'Austria', 'Австрия', 'AT', 'AUT'),
(16, 'Azerbaijan', 'Aserbaidschan', 'AZERBAÏDJAN', 'Azerbaigian', 'Azerbaiyán', 'Азербайджан', 'AZ', 'AZE'),
(17, 'Bahamas', 'Bahamas', 'BAHAMAS', 'Bahamas', 'Bahamas (las)', 'Багамы', 'BS', 'BHS'),
(18, 'Bahrain', 'Bahrain', 'BAHREÏN', 'Bahrein', 'Bahrein', 'Бахрейн', 'BH', 'BHR'),
(19, 'Bangladesh', 'Bangladesch', 'BANGLADESH', 'Bangladesh', 'Bangladesh', 'Бангладеш', 'BD', 'BGD'),
(20, 'Barbados', 'Barbados', 'BARBADE', 'Barbados', 'Barbados', 'Барбадос', 'BB', 'BRB'),
(21, 'Belarus', 'Belarus', 'BÉLARUS', 'Bielorussia', 'Belarús', 'Белоруссия', 'BY', 'BLR'),
(22, 'Belgium', 'Belgien', 'BELGIQUE', 'Belgio', 'Bélgica', 'Бельгия', 'BE', 'BEL'),
(23, 'Belize', 'Belize', 'BELIZE', 'Belize', 'Belice', 'Белиз', 'BZ', 'BLZ'),
(24, 'Benin', 'Benin', 'BÉNIN', 'Benin', 'Benin', 'Бенин', 'BJ', 'BEN'),
(25, 'Bermuda', 'Bermuda', 'BERMUDES', 'Bermuda', 'Bermudas', 'Бермуды', 'BM', 'BMU'),
(26, 'Bhutan', 'Bhutan', 'BHOUTAN', 'Bhutan', 'Bhután', 'Бутан', 'BT', 'BTN'),
(27, 'Bolivia, Plurinational State of', 'Bolivien', 'BOLIVIE, ÉTAT PLURINATIONAL DE', 'Bolivia', 'Bolivia (Estado Plurinacional de)', 'Боливия', 'BO', 'BOL'),
(28, 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius und Saba', 'BONAIRE, SAINT-EUSTACHE ET SABA', 'Isole BES', 'Bonaire, San Eustaquio y Saba', 'Синт-Эстатиус и Саба', 'BQ', 'BES'),
(29, 'Bosnia and Herzegovina', 'Bosnien und Herzegowina', 'BOSNIE-HERZÉGOVINE', 'Bosnia ed Erzegovina', 'Bosnia y Herzegovina', 'Босния и Герцеговина', 'BA', 'BIH'),
(30, 'Botswana', 'Botswana', 'BOTSWANA', 'Botswana', 'Botswana', 'Ботсвана', 'BW', 'BWA'),
(31, 'Bouvet Island', 'Bouvetinsel', 'BOUVET, ÎLE', 'Isola Bouvet', 'Bouvet, Isla', 'Остров Буве', 'BV', ''),
(32, 'Brazil', 'Brasilien', 'BRÉSIL', 'Brasile', 'Brasil', 'Бразилия', 'BR', 'BRA'),
(33, 'British Indian Ocean Territory', 'Britisches Territorium im Indischen Ozean', 'OCÉAN INDIEN, TERRITOIRE BRITANNIQUE DE L\'', 'Territorio britannico dell\'oceano', 'Territorio Británico del Océano Índico (el)', 'Британская территория в Индийском океане', 'IO', ''),
(34, 'Brunei Darussalam', 'Brunei Darussalam', 'BRUNÉI DARUSSALAM', 'Brunei', 'Brunei Darussalam', 'Бруней', 'BN', 'BRN'),
(35, 'Bulgaria', 'Bulgarien', 'BULGARIE', 'Bulgaria', 'Bulgaria', 'Болгария', 'BG', 'BGR'),
(36, 'Burkina Faso', 'Burkina Faso', 'BURKINA FASO', 'Burkina Faso', 'Burkina Faso', 'Буркина-Фасо', 'BF', 'BFA'),
(37, 'Burundi', 'Burundi', 'BURUNDI', 'Burundi', 'Burundi', 'Бурунди', 'BI', 'BDI'),
(38, 'Cambodia', 'Kambodscha', 'CAMBODGE', 'Cambogia ', 'Camboya', 'Камбоджа', 'KH', 'KHM'),
(39, 'Cameroon', 'Kamerun', 'CAMEROUN', 'Camerun', 'Camerún', 'Камерун', 'CM', 'CMR'),
(40, 'Canada', 'Kanada', 'CANADA', 'Canada', 'Canadá', 'Канада', 'CA', 'CAN'),
(41, 'Cape Verde', 'Kap Verde', 'CABO VERDE', 'Capo Verde', 'Cabo Verde', 'Кабо-Верде', 'CV', 'CPV'),
(42, 'Cayman Islands', 'Kaimaninseln', 'CAÏMANES, ÎLES', 'Isole Cayman', 'Caimán, (las) Islas', 'Острова Кайман', 'KY', 'CYM'),
(43, 'Central African Republic', 'Zentralafrikanische Republik', 'CENTRAFRICAINE, RÉPUBLIQUE', 'Rep. Centrafricana', 'República Centroafricana (la)', 'ЦАР', 'CF', 'CAF'),
(44, 'Chad', 'Tschad', 'TCHAD', 'Ciad ', 'Chad', 'Чад', 'TD', 'TCD'),
(45, 'Chile', 'Chile', 'CHILI', 'Cile', 'Chile', 'Чили', 'CL', 'CHL'),
(46, 'China', 'China, Volksrepublik', 'CHINE', 'Cina', 'China', 'КНР (Китайская Народная Республика)', 'CN', 'CHN'),
(47, 'Christmas Island', 'Weihnachtsinsel', 'CHRISTMAS, ÎLE', 'Isola di Natale', 'Navidad, Isla de', 'Остров Рождества', 'CX', ''),
(48, 'Cocos (Keeling) Islands', 'Kokosinseln', 'COCOS (KEELING), ÎLES', 'Isole Cocos (Keeling)', 'Cocos / Keeling, (las) Islas', 'Кокосовые острова', 'CC', ''),
(49, 'Colombia', 'Kolumbien', 'COLOMBIE', 'Colombia', 'Colombia', 'Колумбия', 'CO', 'COL'),
(50, 'Comoros', 'Komoren', 'COMORES', 'Comore ', 'Comoras (las)', 'Коморы', 'KM', 'COM'),
(51, 'Congo', 'Republik Kongo', 'CONGO', 'Rep. del Congo', 'Congo (el)', 'Республика Конго', 'CG', 'COG'),
(52, 'Congo, The Democratic Republic of the', 'Kongo, Demokratische Republik', 'CONGO, LA RÉPUBLIQUE DÉMOCRATIQUE DU', 'RD del Congo', 'Congo (la República Democrática del)', 'Демократическая Республика Конго', 'CD', 'COD'),
(53, 'Cook Islands', 'Cookinseln', 'COOK, ÎLES', 'Isole Cook', 'Cook, (las) Islas', 'Острова Кука', 'CK', 'COK'),
(54, 'Costa Rica', 'Costa Rica', 'COSTA RICA', 'Costa Rica', 'Costa Rica', 'Коста-Рика', 'CR', 'CRI'),
(55, 'Cote d\'Ivoire', 'Elfenbeinküste', 'CÔTE D’IVOIRE', 'Costa d\'Avorio', 'costa de marfil !Côte d\'Ivoire', 'Кот-д’Ивуар', 'CI', 'CIV'),
(56, 'Croatia', 'Kroatien', 'CROATIE', 'Croazia', 'Croacia', 'Хорватия', 'HR', 'HRV'),
(57, 'Cuba', 'Kuba', 'CUBA', 'Cuba', 'Cuba', 'Куба', 'CU', 'CUB'),
(58, 'Curacao', 'Curaçao', 'CURAÇAO', 'Curaçao', 'Curaçao', 'Кюрасао', 'CW', 'CUW'),
(59, 'Cyprus', 'Zypern', 'CHYPRE', 'Cipro', 'Chipre', 'Кипр', 'CY', 'CYP'),
(60, 'Czech Republic', 'Tschechische Republik', 'TCHÈQUE, RÉPUBLIQUE', 'Rep. Ceca', 'República Checa (la)', 'Чехия', 'CZ', 'CZE'),
(61, 'Denmark', 'Dänemark', 'DANEMARK', 'Danimarca', 'Dinamarca', 'Дания', 'DK', 'DNK'),
(62, 'Djibouti', 'Dschibuti', 'DJIBOUTI', 'Gibuti', 'Djibouti', 'Джибути', 'DJ', 'DJI'),
(63, 'Dominica', 'Dominica', 'DOMINIQUE', 'Dominica', 'Dominica', 'Доминика', 'DM', 'DMA'),
(64, 'Dominican Republic', 'Dominikanische Republik', 'DOMINICAINE, RÉPUBLIQUE', 'Rep. Dominicana', 'Dominicana, (la) República', 'Доминиканская Республика', 'DO', 'DOM'),
(65, 'Ecuador', 'Ecuador', 'ÉQUATEUR', 'Ecuador', 'Ecuador', 'Эквадор', 'EC', 'ECU'),
(66, 'Egypt', 'Ägypten', 'ÉGYPTE', 'Egitto', 'Egipto', 'Египет', 'EG', 'EGY'),
(67, 'El Salvador', 'El Salvador', 'EL SALVADOR', 'El Salvador ', 'El Salvador', 'Сальвадор', 'SV', 'SLV'),
(68, 'Equatorial Guinea', 'Äquatorialguinea', 'GUINÉE ÉQUATORIALE', 'Guinea Equatoriale', 'Guinea Ecuatorial', 'Экваториальная Гвинея', 'GQ', 'GNQ'),
(69, 'Eritrea', 'Eritrea', 'ÉRYTHRÉE', 'Eritrea', 'Eritrea', 'Эритрея', 'ER', 'ERI'),
(70, 'Estonia', 'Estland', 'ESTONIE', 'Estonia', 'Estonia', 'Эстония', 'EE', 'EST'),
(71, 'Ethiopia', 'Athiopien!Äthiopien', 'ÉTHIOPIE', 'Etiopia', 'Etiopía', 'Эфиопия', 'ET', 'ETH'),
(72, 'Falkland Islands (Malvinas)', 'Falklandinseln', 'FALKLAND, ÎLES (MALVINAS)', 'Isole Falkland', 'Malvinas [Falkland], (las) Islas', 'Фолклендские острова', 'FK', 'FLK'),
(73, 'Faroe Islands', 'Färöer', 'FÉROÉ, ÎLES', 'Fær Øer', 'Feroe, (las) Islas', 'Фареры', 'FO', 'FRO'),
(74, 'Fiji', 'Fidschi', 'FIDJI', 'Figi', 'Fiji', 'Фиджи', 'FJ', 'FJI'),
(75, 'Finland', 'Finnland', 'FINLANDE', 'Finlandia', 'Finlandia', 'Финляндия', 'FI', 'FIN'),
(76, 'France', 'Frankreich', 'FRANCE', 'Francia', 'Francia', 'Франция', 'FR', 'FRA'),
(77, 'French Guiana', 'Französisch-Guayana', 'GUYANE FRANÇAISE', 'Guyana francese', 'Guayana Francesa', 'Гвиана', 'GF', 'GUF'),
(78, 'French Polynesia', 'Französisch-Polynesien', 'POLYNÉSIE FRANÇAISE', 'Polinesia Francese ', 'Polinesia Francesa', 'Французская Полинезия', 'PF', 'PYF'),
(79, 'French Southern Territories', 'Französische Süd- und Antarktisgebiete', 'TERRES AUSTRALES FRANÇAISES', 'Terre australi e antartiche francesi', 'Tierras Australes Francesas (las)', 'Французские Южные и Антарктические Территории', 'TF', ''),
(80, 'Gabon', 'Gabun', 'GABON', 'Gabon', 'Gabón', 'Габон', 'GA', 'GAB'),
(81, 'Gambia', 'Gambia', 'GAMBIE', 'Gambia', 'Gambia (la)', 'Гамбия', 'GM', 'GMB'),
(82, 'Georgia', 'Georgien', 'GÉORGIE', 'Georgia', 'Georgia', 'Грузия', 'GE', 'GEO'),
(83, 'Germany', 'Deutschland', 'ALLEMAGNE', 'Germania', 'Alemania', 'Германия', 'DE', 'DEU'),
(84, 'Ghana', 'Ghana', 'GHANA', 'Ghana', 'Ghana', 'Гана', 'GH', 'GHA'),
(85, 'Gibraltar', 'Gibraltar', 'GIBRALTAR', 'Gibilterra', 'Gibraltar', 'Гибралтар', 'GI', 'GIB'),
(86, 'Greece', 'Griechenland', 'GRÈCE', 'Grecia ', 'Grecia', 'Греция', 'GR', 'GRC'),
(87, 'Greenland', 'Grönland', 'GROENLAND', 'Groenlandia', 'Groenlandia', 'Гренландия', 'GL', 'GRL'),
(88, 'Grenada', 'Grenada', 'GRENADE', 'Grenada', 'Granada', 'Гренада', 'GD', 'GRD'),
(89, 'Guadeloupe', 'Guadeloupe', 'GUADELOUPE', 'Guadalupa', 'Guadeloupe', 'Гваделупа', 'GP', 'GLP'),
(90, 'Guam', 'Guam', 'GUAM', 'Guam', 'Guam', 'Гуам', 'GU', 'GUM'),
(91, 'Guatemala', 'Guatemala', 'GUATEMALA', 'Guatemala', 'Guatemala', 'Гватемала', 'GT', 'GTM'),
(92, 'Guernsey', 'Guernsey', 'GUERNESEY', 'Guernsey', 'Guernsey', 'Гернси', 'GG', 'GGY'),
(93, 'Guinea', 'Guinea', 'GUINÉE', 'Guinea', 'Guinea', 'Гвинея', 'GN', 'GIN'),
(94, 'Guinea-Bissau', 'Guinea-Bissau', 'GUINÉE-BISSAU', 'Guinea-Bissau', 'Guinea Bissau', 'Гвинея-Бисау', 'GW', 'GNB'),
(95, 'Guyana', 'Guyana', 'GUYANA', 'Guyana', 'Guyana', 'Гайана', 'GY', 'GUY'),
(96, 'Haiti', 'Haiti', 'HAÏTI', 'Haiti ', 'Haití', 'Гаити', 'HT', 'HTI'),
(97, 'Heard Island and McDonald Islands', 'Heard und McDonaldinseln', 'HEARD ET MACDONALD, ÎLES', 'Isole Heard e McDonald', 'Heard (Isla) e Islas McDonald', 'Херд и Макдональд', 'HM', ''),
(98, 'Holy See (Vatican City State)', 'Vatikanstadt', 'SAINT-SIÈGE (ÉTAT DE LA CITÉ DU VATICAN)', 'Città del Vaticano', 'Santa Sede (la)', 'Ватикан', 'VA', 'VAT'),
(99, 'Honduras', 'Honduras', 'HONDURAS', 'Honduras', 'Honduras', 'Гондурас', 'HN', 'HND'),
(100, 'Hong Kong', 'Hongkong', 'HONG KONG', 'Hong Kong', 'Hong Kong', 'Гонконг', 'HK', 'HKG'),
(101, 'Hungary', 'Ungarn', 'HONGRIE', 'Ungheria', 'Hungría', 'Венгрия', 'HU', 'HUN'),
(102, 'Iceland', 'Island', 'ISLANDE', 'Islanda ', 'Islandia', 'Исландия', 'IS', 'ISL'),
(103, 'India', 'Indien', 'INDE', 'India ', 'India', 'Индия Индия', 'IN', 'IND'),
(104, 'Indonesia', 'Indonesien', 'INDONÉSIE', 'Indonesia', 'Indonesia', 'Индонезия', 'ID', 'IDN'),
(105, 'Iran, Islamic Republic of', 'Iran, Islamische Republik', 'IRAN, RÉPUBLIQUE ISLAMIQUE D\'', 'Iran ', 'Irán (República Islámica de)', 'Иран', 'IR', 'IRN'),
(106, 'Iraq', 'Irak', 'IRAQ', 'Iraq ', 'Iraq', 'Ирак', 'IQ', 'IRQ'),
(107, 'Ireland', 'Irland', 'IRLANDE', 'Irlanda ', 'Irlanda', 'Флаг Ирландии Ирландия', 'IE', 'IRL'),
(108, 'Isle of Man', 'Insel Man', 'ÎLE DE MAN', 'Isola di Man', 'Isla de Man', 'Остров Мэн', 'IM', 'IMN'),
(109, 'Israel', 'Israel', 'ISRAËL', 'Israele ', 'Israel', 'Израиль', 'IL', 'ISR'),
(110, 'Italy', 'Italien', 'ITALIE', 'Italia ', 'Italia', 'Италия', 'IT', 'ITA'),
(111, 'Jamaica', 'Jamaika', 'JAMAÏQUE', 'Giamaica', 'Jamaica', 'Ямайка', 'JM', 'JAM'),
(112, 'Japan', 'Japan', 'JAPON', 'Giappone ', 'Japón', 'Япония', 'JP', 'JPN'),
(113, 'Jersey', 'Jersey (Kanalinsel)', 'JERSEY', 'Jersey ', 'Jersey', 'Джерси', 'JE', 'JEY'),
(114, 'Jordan', 'Jordanien', 'JORDANIE', 'Giordania ', 'Jordania', 'Иордания', 'JO', 'JOR'),
(115, 'Kazakhstan', 'Kasachstan', 'KAZAKHSTAN', 'Kazakistan ', 'Kazajstán', 'Казахстан', 'KZ', 'KAZ'),
(116, 'Kenya', 'Kenia', 'KENYA', 'Kenya ', 'Kenya', 'Кения', 'KE', 'KEN'),
(117, 'Kiribati', 'Kiribati', 'KIRIBATI', 'Kiribati ', 'Kiribati', 'Кирибати', 'KI', 'KIR'),
(118, 'Korea, Democratic People\'s Republic of', 'Nordkorea', 'CORÉE, RÉPUBLIQUE POPULAIRE DÉMOCRATIQUE DE', 'Corea del Nord ', 'Corea (la República Popular Democrática de)', 'КНДР (Корейская Народно-Демократическая Республика)', 'KP', 'PRK'),
(119, 'Korea, Republic of', 'Südkorea', 'CORÉE, RÉPUBLIQUE DE', 'Corea del Sud ', 'Corea (la República de)', 'Республика Корея', 'KR', 'KOR'),
(120, 'Kuwait', 'Kuwait', 'KOWEÏT', 'Kuwait ', 'Kuwait', 'Кувейт', 'KW', 'KWT'),
(121, 'Kyrgyzstan', 'Kirgisistan', 'KIRGHIZISTAN', 'Kirghizistan', 'Kirguistán', 'Киргизия', 'KG', 'KGZ'),
(122, 'Lao People\'s Democratic Republic', 'Laos, Demokratische Volksrepublik', 'LAO, RÉPUBLIQUE DÉMOCRATIQUE POPULAIRE', 'Laos ', 'Lao, (la) República Democrática Popular', 'Лаос', 'LA', 'LAO'),
(123, 'Latvia', 'Lettland', 'LETTONIE', 'Lettonia ', 'Letonia', 'Латвия', 'LV', 'LVA'),
(124, 'Lebanon', 'Libanon', 'LIBAN', 'Libano', 'Líbano', 'Ливан', 'LB', 'LBN'),
(125, 'Lesotho', 'Lesotho', 'LESOTHO', 'Lesotho ', 'Lesotho', 'Лесото', 'LS', 'LSO'),
(126, 'Liberia', 'Liberia', 'LIBÉRIA', 'Liberia ', 'Liberia', 'Либерия', 'LR', 'LBR'),
(127, 'Libyan Arab Jamahiriya', 'Libyen', 'LIBYE', 'Libia ', 'Libia', 'Ливия', 'LY', 'LBY'),
(128, 'Liechtenstein', 'Liechtenstein', 'LIECHTENSTEIN', 'Liechtenstein', 'Liechtenstein', 'Лихтенштейн', 'LI', 'LIE'),
(129, 'Lithuania', 'Litauen', 'LITUANIE', 'Lituania', 'Lituania', 'Литва', 'LT', 'LTU'),
(130, 'Luxembourg', 'Luxemburg', 'LUXEMBOURG', 'Lussemburgo', 'Luxemburgo', 'Люксембург', 'LU', 'LUX'),
(131, 'Macao', 'Macau', 'MACAO', 'Macao ', 'Macao', 'Макао', 'MO', 'MAC'),
(132, 'Macedonia, The former Yugoslav Republic of', 'Mazedonien', 'MACÉDOINE, L\'EX-RÉPUBLIQUE YOUGOSLAVE DE', 'Macedonia ', 'Macedonia (la ex República Yugoslava de)', 'Македония', 'MK', 'MKD'),
(133, 'Madagascar', 'Madagaskar', 'MADAGASCAR', 'Madagascar ', 'Madagascar', 'Мадагаскар', 'MG', 'MDG'),
(134, 'Malawi', 'Malawi', 'MALAWI', 'Malawi ', 'Malawi', 'Малави', 'MW', 'MWI'),
(135, 'Malaysia', 'Malaysia', 'MALAISIE', 'Malesia ', 'Malasia', 'Малайзия', 'MY', 'MYS'),
(136, 'Maldives', 'Malediven', 'MALDIVES', 'Maldive ', 'Maldivas', 'Мальдивы', 'MV', 'MDV'),
(137, 'Mali', 'Mali', 'MALI', 'Mali ', 'Malí', 'Мали', 'ML', 'MLI'),
(138, 'Malta', 'Malta', 'MALTE', 'Malta ', 'Malta', 'Мальта', 'MT', 'MLT'),
(139, 'Marshall Islands', 'Marshallinseln', 'MARSHALL, ÎLES', 'Isole Marshall', 'Marshall, (las) Islas', 'Маршалловы Острова', 'MH', 'MHL'),
(140, 'Martinique', 'Martinique', 'MARTINIQUE', 'Martinica', 'Martinique', 'Мартиника', 'MQ', 'MTQ'),
(141, 'Mauritania', 'Mauretanien', 'MAURITANIE', 'Mauritania', 'Mauritania', 'Мавритания', 'MR', 'MRT'),
(142, 'Mauritius', 'Mauritius', 'MAURICE', 'Mauritius', 'Mauricio', 'Маврикий', 'MU', 'MUS'),
(143, 'Mayotte', 'Mayotte', 'MAYOTTE', 'Mayotte ', 'Mayotte', 'Майотта', 'YT', 'MYT'),
(144, 'Mexico', 'Mexiko', 'MEXIQUE', 'Messico ', 'México', 'Мексика', 'MX', 'MEX'),
(145, 'Micronesia, Federated States of', 'Mikronesien', 'MICRONÉSIE, ÉTATS FÉDÉRÉS DE', 'Micronesia', 'Micronesia (Estados Federados de)', 'Микронезия', 'FM', 'FSM'),
(146, 'Moldova, Republic of', 'Moldawien (Republik Moldau)', 'MOLDOVA', 'Moldavia', 'Moldova (la República de)', 'Молдавия', 'MD', 'MDA'),
(147, 'Monaco', 'Monaco', 'MONACO', 'Monaco ', 'Mónaco', 'Монако', 'MC', 'MCO'),
(148, 'Mongolia', 'Mongolei', 'MONGOLIE', 'Mongolia', 'Mongolia', 'Монголия', 'MN', 'MNG'),
(149, 'Montenegro', 'Montenegro', 'MONTÉNÉGRO', 'Montenegro', 'Montenegro', 'Черногория', 'ME', 'MNE'),
(150, 'Montserrat', 'Montserrat', 'MONTSERRAT', 'Montserrat', 'Montserrat', 'Монтсеррат', 'MS', 'MSR'),
(151, 'Morocco', 'Marokko', 'MAROC', 'Marocco', 'Marruecos', 'Марокко', 'MA', 'MAR'),
(152, 'Mozambique', 'Mosambik', 'MOZAMBIQUE', 'Mozambico', 'Mozambique', 'Мозамбик', 'MZ', 'MOZ'),
(153, 'Myanmar', 'Myanmar (Burma)', 'MYANMAR', 'Birmania', 'Myanmar', 'Мьянма', 'MM', 'MMR'),
(154, 'Namibia', 'Namibia', 'NAMIBIE', 'Namibia ', 'Namibia', 'Намибия', 'NA', 'NAM'),
(155, 'Nauru', 'Nauru', 'NAURU', 'Nauru ', 'Nauru', 'Науру', 'NR', 'NRU'),
(156, 'Nepal', 'Nepal', 'NÉPAL', 'Nepal ', 'Nepal', 'Непал', 'NP', 'NPL'),
(157, 'Netherlands', 'Niederlande', 'PAYS-BAS', 'Paesi Bassi', 'Países Bajos (los)', 'Нидерланды', 'NL', 'NLD'),
(158, 'New Caledonia', 'Neukaledonien', 'NOUVELLE-CALÉDONIE', 'Nuova Caledonia', 'Nueva Caledonia', 'Новая Каледония', 'NC', 'NCL'),
(159, 'New Zealand', 'Neuseeland', 'NOUVELLE-ZÉLANDE', 'Nuova Zelanda', 'Nueva Zelandia', 'Новая Зеландия', 'NZ', 'NZL'),
(160, 'Nicaragua', 'Nicaragua', 'NICARAGUA', 'Nicaragua', 'Nicaragua', 'Никарагуа', 'NI', 'NIC'),
(161, 'Niger', 'Niger', 'NIGER', 'Niger ', 'Níger (el)', 'Нигер', 'NE', 'NER'),
(162, 'Nigeria', 'Nigeria', 'NIGÉRIA', 'Nigeria ', 'Nigeria', 'Нигерия', 'NG', 'NGA'),
(163, 'Niue', 'Niue', 'NIUÉ', 'Niue ', 'Niue', 'Ниуэ', 'NU', 'NIU'),
(164, 'Norfolk Island', 'Norfolkinsel', 'NORFOLK, ÎLE', 'Isola Norfolk', 'Norfolk, Isla', 'Остров Норфолк', 'NF', 'NFK'),
(165, 'Northern Mariana Islands', 'Nördliche Marianen', 'MARIANNES DU NORD, ÎLES', 'Isole Marianne Settentrionali', 'Marianas del Norte, (las) Islas', 'Северные Марианские острова', 'MP', 'MNP'),
(166, 'Norway', 'Norwegen', 'NORVÈGE', 'Norvegia ', 'Noruega', 'Норвегия', 'NO', 'NOR'),
(167, 'Oman', 'Oman', 'OMAN', 'Oman ', 'Omán', 'Оман', 'OM', 'OMN'),
(168, 'Pakistan', 'Pakistan', 'PAKISTAN', 'Pakistan ', 'Pakistán', 'Пакистан', 'PK', 'PAK'),
(169, 'Palau', 'Palau', 'PALAOS', 'Palau ', 'Palau', 'Палау', 'PW', 'PLW'),
(170, 'Palestinian Territory, Occupied', 'Palästina', 'ÉTAT DE PALESTINE', 'Palestina ', 'Palestina, Estado de', 'Государство Палестина', 'PS', 'PSE'),
(171, 'Panama', 'Panama', 'PANAMA', 'Panamá', 'Panamá', 'Панама', 'PA', 'PAN'),
(172, 'Papua New Guinea', 'Papua-Neuguinea', 'PAPOUASIE-NOUVELLE-GUINÉE', 'Papua Nuova Guinea ', 'Papua Nueva Guinea', 'Папуа — Новая Гвинея', 'PG', 'PNG'),
(173, 'Paraguay', 'Paraguay', 'PARAGUAY', 'Paraguay ', 'Paraguay', 'Парагвай', 'PY', 'PRY'),
(174, 'Peru', 'Peru', 'PÉROU', 'Perù ', 'Perú', 'Перу', 'PE', 'PER'),
(175, 'Philippines', 'Philippinen', 'PHILIPPINES', 'Filippine ', 'Filipinas (las)', 'Филиппины', 'PH', 'PHL'),
(176, 'Pitcairn', 'Pitcairninseln', 'PITCAIRN', 'Isole Pitcairn ', 'Pitcairn', 'Острова Питкэрн', 'PN', 'PCN'),
(177, 'Poland', 'Polen', 'POLOGNE', 'Polonia ', 'Polonia', 'Польша', 'PL', 'POL'),
(178, 'Portugal', 'Portugal', 'PORTUGAL', 'Portogallo ', 'Portugal', 'Португалия', 'PT', 'PRT'),
(179, 'Puerto Rico', 'Puerto Rico', 'PORTO RICO', 'Porto Rico ', 'Puerto Rico', 'Пуэрто-Рико', 'PR', 'PRI'),
(180, 'Qatar', 'Katar', 'QATAR', 'Qatar ', 'Qatar', 'Катар', 'QA', 'QAT'),
(181, 'Reunion', 'Réunion', 'RÉUNION', 'Riunione ', 'Reunión', 'Реюньон', 'RE', 'REU'),
(182, 'Romania', 'Rumänien', 'ROUMANIE', 'Romania ', 'Rumania', 'Румыния', 'RO', 'ROU'),
(183, 'Russian Federation', 'Russische Föderation', 'RUSSIE, FÉDÉRATION DE', 'Russia ', 'Rusia, (la) Federación de', 'Россия', 'RU', 'RUS'),
(184, 'Rwanda', 'Ruanda', 'RWANDA', 'Ruanda ', 'Rwanda', 'Руанда', 'RW', 'RWA'),
(185, 'Saint Barthelemy', 'Saint-Barthélemy', 'SAINT-BARTHÉLEMY', 'Saint-Barthélemy', 'Saint Barthélemy', 'Сен-Бартелеми', 'BL', 'BLM'),
(186, 'Saint Helena, Ascension and Tristan Da Cunha', 'St. Helena', 'SAINTE-HÉLÈNE, ASCENSION ET TRISTAN DA CUNHA', 'Sant\'Elena, Ascensione e Tristan da Cunha', 'Santa Helena, Ascensión y Tristán de Acuña', 'Острова Святой Елены, Вознесения и Тристан-да-Кунья', 'SH', 'SHN'),
(187, 'Saint Kitts and Nevis', 'St. Kitts und Nevis', 'SAINT-KITTS-ET-NEVIS', 'Saint Kitts e Nevis', 'Saint Kitts y Nevis', 'Сент-Китс и Невис', 'KN', 'KNA'),
(188, 'Saint Lucia', 'St. Lucia', 'SAINTE-LUCIE', 'Santa Lucia', 'Santa Lucía', 'Сент-Люсия', 'LC', 'LCA'),
(189, 'Saint Martin (French Part)', 'Saint-Martin (franz. Teil)', 'SAINT-MARTIN (PARTIE FRANÇAISE)', 'Saint-Martin', 'Saint Martin (parte francesa)', 'Сен-Мартен', 'MF', 'MAF'),
(190, 'Saint Pierre and Miquelon', 'Saint-Pierre und Miquelon', 'SAINT-PIERRE-ET-MIQUELON', 'Saint-Pierre e Miquelon', 'San Pedro y Miquelón', 'Сен-Пьер и Микелон', 'PM', 'SPM'),
(191, 'Saint Vincent and The Grenadines', 'St. Vincent und die Grenadinen', 'SAINT-VINCENT-ET-LES-GRENADINES', 'Saint Vincent e Grenadine', 'San Vicente y las Granadinas', 'Сент-Винсент и Гренадины', 'VC', 'VCT'),
(192, 'Samoa', 'Samoa', 'SAMOA', 'Samoa ', 'Samoa', 'Самоа', 'WS', 'WSM'),
(193, 'San Marino', 'San Marino', 'SAINT-MARIN', 'San Marino ', 'San Marino', 'Сан-Марино', 'SM', 'SMR'),
(194, 'Sao Tome and Principe', 'São Tomé und Príncipe', 'SAO TOMÉ-ET-PRINCIPE', 'São Tomé e Príncipe', 'Santo Tomé y Príncipe', 'Сан-Томе и Принсипи', 'ST', 'STP'),
(195, 'Saudi Arabia', 'Saudi-Arabien', 'ARABIE SAOUDITE', 'Arabia Saudita', 'Arabia Saudita', 'Саудовская Аравия', 'SA', 'SAU'),
(196, 'Senegal', 'Senegal', 'SÉNÉGAL', 'Senegal ', 'Senegal', 'Сенегал', 'SN', 'SEN'),
(197, 'Serbia', 'Serbien', 'SERBIE', 'Serbia ', 'Serbia', 'Сербия', 'RS', 'SRB'),
(198, 'Seychelles', 'Seychellen', 'SEYCHELLES', 'Seychelles', 'Seychelles', 'Сейшельские Острова', 'SC', 'SYC'),
(199, 'Sierra Leone', 'Sierra Leone', 'SIERRA LEONE', 'Sierra Leone', 'Sierra leona', 'Сьерра-Леоне', 'SL', 'SLE'),
(200, 'Singapore', 'Singapur', 'SINGAPOUR', 'Singapore', 'Singapur', 'Сингапур', 'SG', 'SGP'),
(201, 'Sint Maarten (Dutch Part)', 'Sint Maarten (niederl. Teil)', 'SAINT-MARTIN (PARTIE NÉERLANDAISE)', 'Sint Maarten ', 'Sint Maarten (parte neerlandesa)', 'Синт-Мартен', 'SX', 'SXM'),
(202, 'Slovakia', 'Slowakei', 'SLOVAQUIE', 'Slovacchia ', 'Eslovaquia', 'Словакия', 'SK', 'SVK'),
(203, 'Slovenia', 'Slowenien', 'SLOVÉNIE', 'Slovenia Slovenia', 'Eslovenia', 'Словения', 'SI', 'SVN'),
(204, 'Solomon Islands', 'Salomonen', 'SALOMON, ÎLES', 'Isole Salomone', 'Salomón, Islas', 'Соломоновы Острова', 'SB', 'SLB'),
(205, 'Somalia', 'Somalia', 'SOMALIE', 'Somalia ', 'Somalia', 'Сомали', 'SO', 'SOM'),
(206, 'South Africa', 'Südafrika', 'AFRIQUE DU SUD', 'Sudafrica ', 'Sudáfrica', 'ЮАР', 'ZA', 'ZAF'),
(207, 'South Georgia and The South Sandwich Islands', 'Südgeorgien und die Südlichen Sandwichinseln', 'GÉORGIE DU SUD ET LES ÎLES SANDWICH DU SUD', 'Georgia del Sud e isole Sandwich meridionali', 'Georgia del Sur (la) y las Islas Sandwich del Sur', 'Южная Георгия и Южные Сандвичевы Острова', 'GS', ''),
(208, 'South Sudan', 'Sudsudan!Südsudan', 'SOUDAN DU SUD', 'Sudan del Sud', 'Sudán del Sur', 'Южный Судан', 'SS', 'SSD'),
(209, 'Spain', 'Spanien', 'ESPAGNE', 'Spagna', 'España', 'Испания', 'ES', 'ESP'),
(210, 'Sri Lanka', 'Sri Lanka', 'SRI LANKA', 'Sri Lanka ', 'Sri Lanka', 'Шри-Ланка', 'LK', 'LKA'),
(211, 'Sudan', 'Sudan', 'SOUDAN', 'Sudan ', 'Sudán (el)', 'Судан', 'SD', 'SDN'),
(212, 'Suriname', 'Suriname', 'SURINAME', 'Suriname', 'Suriname', 'Суринам', 'SR', 'SUR'),
(213, 'Svalbard and Jan Mayen', 'Svalbard und Jan Mayen', 'SVALBARD ET ÎLE JAN MAYEN', 'Svalbard e Jan Mayen', 'Svalbard y Jan Mayen', 'Флаг Шпицбергена и Ян-Майена Шпицберген и Ян-Майен', 'SJ', 'SJM'),
(214, 'Swaziland', 'Swasiland', 'SWAZILAND', 'Swaziland', 'Swazilandia', 'Свазиленд', 'SZ', 'SWZ'),
(215, 'Sweden', 'Schweden', 'SUÈDE', 'Svezia', 'Suecia', 'Швеция', 'SE', 'SWE'),
(216, 'Switzerland', 'Schweiz', 'SUISSE', 'Svizzera', 'Suiza', 'Швейцария', 'CH', 'CHE'),
(217, 'Syrian Arab Republic', 'Syrien, Arabische Republik', 'SYRIENNE, RÉPUBLIQUE ARABE', 'Siria ', 'República Árabe Siria', 'Сирия', 'SY', 'SYR'),
(218, 'Taiwan, Province of China', 'Taiwan', 'TAÏWAN, PROVINCE DE CHINE', 'Taiwan ', 'Taiwán (Provincia de China)', 'Китайская Республика', 'TW', ''),
(219, 'Tajikistan', 'Tadschikistan', 'TADJIKISTAN', 'Tagikistan', 'Tayikistán', 'Таджикистан', 'TJ', 'TJK'),
(220, 'Tanzania, United Republic of', 'Tansania, Vereinigte Republik', 'TANZANIE, RÉPUBLIQUE UNIE DE', 'Tanzania ', 'Tanzania, República Unida de', 'Танзания', 'TZ', 'TZA'),
(221, 'Thailand', 'Thailand', 'THAÏLANDE', 'Thailandia', 'Tailandia', 'Таиланд', 'TH', 'THA'),
(222, 'Timor-Leste', 'Osttimor (Timor-Leste)', 'TIMOR-LESTE', 'Timor Est', 'Timor-Leste', 'Восточный Тимор', 'TL', 'TLS'),
(223, 'Togo', 'Togo', 'TOGO', 'Togo ', 'Togo', 'Того', 'TG', 'TGO'),
(224, 'Tokelau', 'Tokelau', 'TOKELAU', 'Tokelau ', 'Tokelau', 'Токелау', 'TK', 'TKL'),
(225, 'Tonga', 'Tonga', 'TONGA', 'Tonga ', 'Tonga', 'Тонга', 'TO', 'TON'),
(226, 'Trinidad and Tobago', 'Trinidad und Tobago', 'TRINITÉ-ET-TOBAGO', 'Trinidad e Tobago', 'Trinidad y Tabago', 'Тринидад и Тобаго', 'TT', 'TTO'),
(227, 'Tunisia', 'Tunesien', 'TUNISIE', 'Tunisia ', 'Túnez', 'Тунис', 'TN', 'TUN'),
(228, 'Turkey', 'Türkei', 'TURQUIE', 'Turchia', 'Turquía', 'Турция', 'TR', 'TUR'),
(229, 'Turkmenistan', 'Turkmenistan', 'TURKMÉNISTAN', 'Turkmenistan', 'Turkmenistán', 'Туркмения', 'TM', 'TKM'),
(230, 'Turks and Caicos Islands', 'Turks- und Caicosinseln', 'TURKS ET CAÏQUES, ÎLES', 'Turks e Caicos ', 'Turcas y Caicos, (las) Islas', 'Тёркс и Кайкос', 'TC', 'TCA'),
(231, 'Tuvalu', 'Tuvalu', 'TUVALU', 'Tuvalu ', 'Tuvalu', 'Тувалу', 'TV', 'TUV'),
(232, 'Uganda', 'Uganda', 'OUGANDA', 'Uganda ', 'Uganda', 'Уганда', 'UG', 'UGA'),
(233, 'Ukraine', 'Ukraine', 'UKRAINE', 'Ucraina ', 'Ucrania', 'Украина', 'UA', 'UKR'),
(234, 'United Arab Emirates', 'Vereinigte Arabische Emirate', 'ÉMIRATS ARABES UNIS', 'Emirati Arabi Uniti', 'Emiratos Árabes Unidos (los)', 'ОАЭ', 'AE', 'ARE'),
(235, 'United Kingdom', 'Vereinigtes Königreich Großbritannien und Nordirland', 'ROYAUME-UNI', 'Regno Unito', 'Reino Unido de Gran Bretaña e Irlanda del Norte (el)', 'Великобритания', 'GB', 'GBR'),
(236, 'United States', 'Vereinigte Staaten von Amerika', 'ÉTATS-UNIS', 'Stati Uniti', 'Estados Unidos de América (los)', 'США', 'US', 'USA'),
(237, 'United States Minor Outlying Islands', 'United States Minor Outlying Islands', 'ÎLES MINEURES ÉLOIGNÉES DES ÉTATS-UNIS', 'Isole minori esterne degli Stati Uniti', 'Islas Ultramarinas Menores de los Estados Unidos (las)', 'Внешние малые острова (США)', 'UM', ''),
(238, 'Uruguay', 'Uruguay', 'URUGUAY', 'Uruguay ', 'Uruguay', 'Уругвай', 'UY', 'URY'),
(239, 'Uzbekistan', 'Usbekistan', 'OUZBÉKISTAN', 'Uzbekistan', 'Uzbekistán', 'Узбекистан', 'UZ', 'UZB'),
(240, 'Vanuatu', 'Vanuatu', 'VANUATU', 'Vanuatu', 'Vanuatu', 'Вануату', 'VU', 'VUT'),
(241, 'Venezuela, Bolivarian Republic of', 'Venezuela', 'VENEZUELA, RÉPUBLIQUE BOLIVARIENNE DU', 'Venezuela ', 'Venezuela (República Bolivariana de)', 'Венесуэла', 'VE', 'VEN'),
(242, 'Viet Nam', 'Vietnam', 'VIET NAM', 'Vietnam', 'Viet Nam', 'Вьетнам', 'VN', 'VNM'),
(243, 'Virgin Islands, British', 'Britische Jungferninseln', 'ÎLES VIERGES BRITANNIQUES', 'Isole Vergini britanniche ', 'Vírgenes británicas, Islas', 'Британские Виргинские острова', 'VG', 'VGB'),
(244, 'Virgin Islands, U.S.', 'Amerikanische Jungferninseln', 'ÎLES VIERGES DES ÉTATS-UNIS', 'Isole Vergini americane ', 'Vírgenes de los Estados Unidos, Islas', 'Виргинские Острова (США)', 'VI', 'VIR'),
(245, 'Wallis and Futuna', 'Wallis und Futuna', 'WALLIS-ET-FUTUNA', 'Wallis e Futuna', 'Wallis y Futuna', 'Уоллис и Футуна', 'WF', 'WLF'),
(246, 'Western Sahara', 'Westsahara', 'SAHARA OCCIDENTAL', 'Sahara Occidentale', 'Sahara Occidental', 'САДР', 'EH', 'ESH'),
(247, 'Yemen', 'Jemen', 'YÉMEN', 'Yemen ', 'Yemen', 'Йемен', 'YE', 'YEM'),
(248, 'Zambia', 'Sambia', 'ZAMBIE', 'Zambia ', 'Zambia', 'Замбия', 'ZM', 'ZMB'),
(249, 'Zimbabwe', 'Simbabwe', 'ZIMBABWE', 'Zimbabwe', 'Zimbabwe', 'Зимбабве', 'ZW', 'ZWE');
